config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  post '/rate' => 'rater#create', :as => 'rate'
  namespace :api do
    namespace :v1 do
      resources :players
      resources :sessions
      resources :users
      resources :sports
      resources :tasks
      match 'user' => 'users#show', :via=> :get
    end
  end

  devise_for :users

  resources :home do
    collection do
      get :profile
    end
   end
   root to: "home#index"
   get 'profile', to: 'home#profile'
   get 'my_sports', to: 'players#my_sports'
   resources :players
   resources :sports
   resources :tasks do
    collection do
      put :update_task
    end
  end

   resources :posts
   

end

app/models/sport.rb
class Sport < ActiveRecord::Base
	belongs_to :player
	# self.inheritance_column = nil
end

app/controllers/api/v1/sports_controller.rb
class Api::V1::SportsController < Api::V1::BaseController

	def index
		respond_with(Sport.all)
	end

	def create
		sport = Sport.create(sport_params)
		if sport.valid?
			render json:{:status=>true,:message=> "Sport Created Successfully",:sport=>sport}
		else
			render json:{:status=>false,:error => sport.errors.full_messages}	
		end
	end

	private
	def sport_params
		params.require(:sport).permit(:name,:sport_type)
	end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
	before_filter :login_required
    before_filter :admin_required,only: [:sport_manage_form]
	def index
		@sports=Sport.all
	end
	def new
		@sport=Sport.new
		Sport.reset_column_information
		Sport.column_names.delete("created_at")
		Sport.column_names.delete("id")
		Sport.column_names.delete("player_id")
		Sport.column_names.delete("updated_at")
		@fields=Sport.column_names
	end
	def show
		@sport=Sport.find params[:id]
	end

	def create
		@sport=Sport.new(sport_params)
		if @sport.save
			redirect_to sports_path
		else
			redirect_to new_sport_path
		end
	end
	def edit
		@sport=Sport.find params[:id]
		render "new"
	end
	def update
		@sport=Sport.find params[:id]
		if @sport.update_attributes(sport_params)
		flash[:notice]="The record was successfully updated"
		end
       redirect_to sports_path

	end
	def destroy
		@sport=Sport.find params[:id]
		if @sport.delete
		   flash[:notice]="The record is deleted successfully"
		   redirect_to sports_path
		end
	end


	def sport_manage_form
		@sport_fields=Sport.column_names
		if request.post?
			require 'rake'
			name=params[:field][:name]
			type=params[:field][:type]
			`rails g migration add_#{name}_to_sports #{name}:#{type}`
			`rake db:migrate`					
			Sport.reset_column_information
			@sport_fields=Sport.column_names
			flash[:notice]="The field added successfully"
		end
	end
	private

# Never trust parameters from the scary internet, only allow the white list through.
def sport_params
  params.require(:sport).permit!
end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/index.html.erb
<%unless flash[:notice].blank?%>
<%=flash[:notice]%>
<%end%>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Players</div>
<%unless @sports.empty?%>
<table class ="table">
	<tr>
		<td>Name</td>
		<td>Type</td>
	</tr>
	<tbody>
	<%@sports.each do |sport|%>
	<tr>
		<td><%=sport.name%></td>
		<td><%=sport.sport_type%></td>
		<br/>
		<td><%=link_to "Edit", edit_sport_path(sport)%></td>
		<td><%=link_to "Delete", sport_path(sport),method: :Delete%></td>
	</tr>

	<%end%>	
	</tbody>
	
</table>
<%else%>
<b>Still,no records available</b>
<%end%>
</div>

app/views/sports/new.html.erb
<%=form_for @sport do |f|%>
<%=f.label :name%>
<%=f.text_field :name,:required=>true,:class=>"input-group"%><br/>
<%=f.label :sport_type%>
<%=f.text_field :sport_type,:required=>true,:class=>"input-group"%><br/>
<%=f.submit "Create Sport"%>

<%end%>

app/views/sports/show.html.erb
show.html.erb

app/views/sports/sport_manage_form.html.erb
<%=flash[:notice] unless flash[:notice].nil?%>

<table>
	<thead>
		<tr>
			<td>Fields</td>
		</tr>
	</thead>
	<tbody>
	<%@sport_fields.each do |field|%>
	<tr>
		<td>
			<%=field%>
		</td>
	</tr>

	<%end%>	
	</tbody>

</table>
<%=simple_form_for :field do |f|%>
<%=f.input :name%>
<%=f.input :type,as: :select,collection: ["binary","boolean","date","datetime","decimal","float","integer","primary_key","references","string","text","time","timestamp"],prompt: "Select input type"%>
<%=f.submit%>


<%end%>