config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  post '/rate' => 'rater#create', :as => 'rate'
  namespace :api do
    namespace :v1 do
      resources :players
      resources :sessions
      resources :users
      resources :sports
      resources :tasks
      match 'user' => 'users#show', :via=> :get
    end
  end

  devise_for :users

  resources :home do
    collection do
      get :profile
    end
   end
   root to: "home#index"
   get 'profile', to: 'home#profile'
   get 'my_sports', to: 'players#my_sports'
   resources :players
   resources :sports
   resources :tasks do
    collection do
      put :update_task
    end
  end

   resources :posts
   

end

app/models/player.rb
class Player < ActiveRecord::Base
 has_many :sports
 has_one :user , :dependent => :destroy
 accepts_nested_attributes_for :user
end

app/controllers/api/v1/players_controller.rb
class Api::V1::PlayersController < Api::V1::BaseController
	
	before_filter :player, :only =>[:update,:destroy]

	def index
		respond_with(Player.all)
	end

	def create
		@player=Player.new player_params
		@player.sports << Sport.find(params[:sports]) unless params[:sports].blank?
		if @player.save
			gb = Gibbon::API.new
			list = gb.lists.list({:filters => {:list_name => "NetSolutions"}})
			gb.lists.subscribe({:id => list["data"].first["id"], :email => {:email => params[:player][:user_attributes][:email]}, :merge_vars => {:FNAME => params[:player][:first_name],:LNAME => params[:player][:last_name], :double_optin => false}})
			current_req.update_attributes(:response => "200 ok")
			render action: :create
		else
			current_req.update_attributes(:response => "400 failed")
			render json:{:status=> false,:errors=>@player.errors.full_messages}
		end
	end

	def update
		@player.sports << Sport.find(params[:sports]) unless params[:sports].blank?
		if @player.update_attributes(player_params)
			current_req.update_attributes(:response => "200 ok")
			render json:{:status=>true,:message=>"Player Updated successfully"}
		else
			current_req.update_attributes(:response => "400 failed")
			render json:{:status=>false,:errors => @player.errors.full_messages}
		end
    end

	def destroy
		if @player.destroy
			current_req.update_attributes(:response => "200 ok")
			render json:{:status=>true,:message=>"Player Deleted Sussessfully"}
		else
			current_req.update_attributes(:response => "400 failed")
			render json:{:status=>false,:message=>"Unable to Delete Player"}
		end
	end

	private

	def player_params
		params.require(:player).permit!
	end

	def player
		@player = Player.find(params[:id])
		rescue ActiveRecord::RecordNotFound
  			render json: {:status=> 404 ,:error => "Record Not Found"}
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	before_filter :login_required
	def index
		@players=Player.all

	end
	def new
		@player=Player.new
		@sports=Sport.all
		@player.build_user
		@photo = @player.user.photos.build
		


	end
	def show
		@player=Player.find params[:id]
		@date = params[:month] ? Date.parse(params[:month]) : Date.today
		@tasks = current_user.tasks
	end

	def create
		@player=Player.new player_params
		@player.sports << Sport.find(params[:sports]) unless params[:sports].nil?
		if @player.save
			# gb = Gibbon::API.new
			# list = gb.lists.list({:filters => {:list_name => "NetSolutions"}})
			# gb.lists.subscribe({:id => list["data"].first["id"], :email => {:email => params[:player][:user_attributes][:email]}, :merge_vars => {:FNAME => params[:player][:first_name], :LNAME => params[:player][:last_name]}, :double_optin => false})
			redirect_to players_path
		else
			redirect_to new_player_path
		end
	end
	def edit
		@player=Player.find params[:id]
		@sports=Sport.all		
	end
	def update
		@player=Player.find params[:id]
		@player.sports << Sport.find(params[:sports]) unless params[:sports].nil?
		if @player.update_attributes(player_params)
		flash[:notice]="The record was successfully updated."
	else
		puts "i am in update error"
		end
       redirect_to players_path

	end
	def destroy
		@player=Player.find params[:id]
		if @player.destroy
		   flash[:notice]="The record was successfully deleted."
		   redirect_to players_path
		end
	end

	def my_sports
		@sports=current_user.player.sports

	end

private
def player_params
  params.require(:player).permit(:first_name,:last_name,:age,user_attributes: [:id,:email,:password,:password_confirmation,photos_attributes: [:image,:id,:_destroy,:avatar]])
end

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/edit.html.erb
<%=form_for(@player) do |f|%>
<%=f.label :first_name%>
<%=f.text_field :first_name,:required=>true%><br/>
<%=f.label :last_name%>
<%=f.text_field :last_name,:required=>true%><br/>
<%=f.label :age%>
<%=f.text_field :age,:required=>true%><br/>
<%=f.fields_for :user do |u|%>
	<%=u.fields_for :photos do |p|%>
			<%=p.file_field :image%>
      <%= image_tag(p.object.image.url) %>
      <%= p.check_box :_destroy %>
      
	<%end%>
<%end%>
</br>
<%= f.label :sports %>
<%= select_tag("sports[]", options_for_select(@sports.collect { |ff| [ff.name, ff.id] }, @player.sports.collect { |fs| fs }),{:multiple=>true, :id => "player_sports"}) %>
<%=f.submit "Update Player"%>

<%end%>

app/views/players/index.html.erb
<%unless flash[:notice].blank?%>
<%=flash[:notice]%>
<%end%>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Players</div>
<%unless @players.empty?%>
<table class="table">
	<tr>
		<td>First Name</td>
		<td>Last Name</td>
		<td>Email</td>
		<td>Age</td>
		<td>sports</td>
		<td>Image</td>
	</tr>
	<tbody>
	<%@players.each do |player|%>
	<tr>
		<td><%=player.first_name%></td>
		<td><%=player.last_name%></td>
		<td><%=player.user.email%></td>
		<td><%=player.age%></td>
		<td><%=player.sports.map do |m| m.name end%></td>
		<%if player.user.photos.count > 0%>
		<td>
			<%player.user.photos.each do |photo|%>
				<%=image_tag(photo.image,height: '32', width: '32')%>
			<%end%></td>
		<%else%>
			<td></td>
		<%end%>
		
		<td><%=link_to "Show", player_path(player)%></td>
		<td><%=link_to "Edit", edit_player_path(player)%></td>
		<td><%=link_to "Delete", player_path(player),method: :Delete%></td>
	</tr>

	<%end%>	
	</tbody>
	
</table>
<%else%>
<b>No records available</b>
<%end%>
</div>

app/views/players/my_sports.html.erb
<%unless @sports.empty?%>
<table>
	<tr>
		<td>Name</td>
		<td>Type</td>
	</tr>
	<tbody>
	<%@sports.each do |sport|%>
	<tr>
		<td><%=sport.name%></td>
		<td><%=sport.sport_type%></td>
		<br/>
	</tr>
	<%end%>	
	</tbody>	
</table>
<%else%>
<b>Still,no records available</b>
<%end%>

app/views/players/new.html.erb
<%=form_for(@player,:html=>{:multipart => true}) do |f|%>
<%=f.label :first_name%>
<%=f.text_field :first_name,:required=>true,:class=>"input-group"%>
<%=f.label :last_name%>
<%=f.text_field :last_name,:required=>true,:class=>"input-group"%>
<%=f.label :age%>
<%=f.text_field :age,:required=>true,:class=>"input-group"%>
<%=f.fields_for :user do |u|%>
<%=u.label :email%>
<%=u.email_field :email,:class=>"input-group"%>
<%=u.label :password%>
<%=u.password_field :password,:class=>"input-group"%>
<%=u.label :password_confirmation%>
<%=u.password_field :password_confirmation,:class=>"input-group"%>

<%=u.fields_for :photos do |p|%>
	<%=p.file_field :image%>
	<%=p.label :avatar%>
	<%=p.check_box :avatar%>
<%end%>
<%end%></br>
<%= f.label :sports %>
<%= select_tag("sports[]", options_for_select(@sports.collect { |ff| [ff.name, ff.id] }, @player.sports.collect { |fs| fs }),{:multiple=>true, :id => "player_sports",:class=>"input-group"}) %>
<%=f.submit "Create Player"%>

<%end%>

app/views/players/player_manage_form.html.erb
<%=flash[:notice] unless flash[:notice].nil?%>

<table>
	<thead>
		<tr>
			<td>Fields</td>
		</tr>
	</thead>
	<tbody>
	<%@player_fields.each do |field|%>
	<tr>
		<td>
			<%=field%>
		</td>
	</tr>

	<%end%>	
	</tbody>

</table>
<%=simple_form_for :field do |f|%>
<%=f.input :name%>
<%=f.input :type,as: :select,collection: ["binary","boolean","date","datetime","decimal","float","integer","primary_key","references","string","text","time","timestamp"],prompt: "Select input type"%>

<%=f.submit%>


<%end%>

app/views/players/show.html.erb
<div id="calendar" class="tinymice">
  <h2 id="month">
    <%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m-01") %>
    <%= h @date.strftime("%B %Y") %>
    <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m-01") %>
  </h2>
 <%= calendar_for(@tasks.order('id'),:year => @date.year, :month => @date.month ) do |t| %>
  <%= t.head('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun') %>
  <%= t.day(:day_method => :created_at) do |date, tasks| %>
    <%= date.day %>
    <ul>
    <% tasks.each do |task| %>
    
    <a href="#" class ="task" data-id=<%=task.id%>><%= task.name%></a>

    <div class="modal fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&amp;times;</button>
            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                <input type="text" class="task_name">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="save_task">Save changes</button>
        </div>
    </div>
  </div>
</div>
    <!-- <li><a href="javascript:void(null);" class="task" data-description="<%= task.name%>"><%=task.name%></a></li> -->
     
    <!-- <div id="dialog-modal" title="Basic modal dialog" style="display: none;"> -->
        
    </div>
      
    <% end %>
  </ul>
  <% end %>
<% end %>
</div>

<%unless @player.nil?%>
<li><%=@player.first_name%></li>
<li><%=@player.user.email%></li>
<%if @player.user.photos.count > 0 %>
  <li>
    <%@player.user.photos.each do |photo|%>
      <%=image_tag(photo.image,height: '32', width: '32')%>
    <%end%>
  </li>
<%end%>
<%end%>