config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  post '/rate' => 'rater#create', :as => 'rate'
  namespace :api do
    namespace :v1 do
      resources :players
      resources :sessions
      resources :users
      resources :sports
      resources :tasks
      match 'user' => 'users#show', :via=> :get
    end
  end

  devise_for :users

  resources :home do
    collection do
      get :profile
    end
   end
   root to: "home#index"
   get 'profile', to: 'home#profile'
   get 'my_sports', to: 'players#my_sports'
   resources :players
   resources :sports
   resources :tasks do
    collection do
      put :update_task
    end
  end

   resources :posts
   

end

app/models/api_request.rb
class ApiRequest < ActiveRecord::Base
	belongs_to :user
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :attachable ,:polymorphic => true
	mount_uploader :image, ImageUploader
end

app/models/player.rb
class Player < ActiveRecord::Base
 has_many :sports
 has_one :user , :dependent => :destroy
 accepts_nested_attributes_for :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	
 self.per_page = 10

 def timestamp
  created_at.strftime('%d %B %Y %H:%M:%S')
end
	
end

app/models/sport.rb
class Sport < ActiveRecord::Base
	belongs_to :player
	# self.inheritance_column = nil
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   belongs_to :player 
   has_many :api_requests
   has_many :tasks
   before_save :generate_token
   has_many :photos, :as => :attachable
   has_one :avatar, :class_name => 'Photo', :as => :attachable
   accepts_nested_attributes_for :photos, allow_destroy: true
   
   def generate_token
   	 self.access_token = SecureRandom.hex
   end     

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
		if current_user
			redirect_to profile_path
		else
			redirect_to new_user_session_path
		end
	end

	def profile
		@photos = current_user.photos
		@photo = current_user.photos.new
	end

	def create
		@photo = current_user.photos.create photo_params
		redirect_to profile_path
	end

	# def update
	# 	@user = User.find(params[:id])
	# 	@user.update_attributes user_params
	# 	redirect_to profile_path
		

	# end

	private

	def photo_params
		params.require(:photo).permit!
	end
	
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	before_filter :login_required
	def index
		@players=Player.all

	end
	def new
		@player=Player.new
		@sports=Sport.all
		@player.build_user
		@photo = @player.user.photos.build
		


	end
	def show
		@player=Player.find params[:id]
		@date = params[:month] ? Date.parse(params[:month]) : Date.today
		@tasks = current_user.tasks
	end

	def create
		@player=Player.new player_params
		@player.sports << Sport.find(params[:sports]) unless params[:sports].nil?
		if @player.save
			# gb = Gibbon::API.new
			# list = gb.lists.list({:filters => {:list_name => "NetSolutions"}})
			# gb.lists.subscribe({:id => list["data"].first["id"], :email => {:email => params[:player][:user_attributes][:email]}, :merge_vars => {:FNAME => params[:player][:first_name], :LNAME => params[:player][:last_name]}, :double_optin => false})
			redirect_to players_path
		else
			redirect_to new_player_path
		end
	end
	def edit
		@player=Player.find params[:id]
		@sports=Sport.all		
	end
	def update
		@player=Player.find params[:id]
		@player.sports << Sport.find(params[:sports]) unless params[:sports].nil?
		if @player.update_attributes(player_params)
		flash[:notice]="The record was successfully updated."
	else
		puts "i am in update error"
		end
       redirect_to players_path

	end
	def destroy
		@player=Player.find params[:id]
		if @player.destroy
		   flash[:notice]="The record was successfully deleted."
		   redirect_to players_path
		end
	end

	def my_sports
		@sports=current_user.player.sports

	end

private
def player_params
  params.require(:player).permit(:first_name,:last_name,:age,user_attributes: [:id,:email,:password,:password_confirmation,photos_attributes: [:image,:id,:_destroy,:avatar]])
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	def index
		@posts = Post.all.paginate(page: params[:page], per_page: 10).order('created_at DESC')
		# sleep(5)
		respond_to do |format|
  			format.html
  			format.js
		end
	end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_i, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end

end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
	before_filter :login_required
    before_filter :admin_required,only: [:sport_manage_form]
	def index
		@sports=Sport.all
	end
	def new
		@sport=Sport.new
		Sport.reset_column_information
		Sport.column_names.delete("created_at")
		Sport.column_names.delete("id")
		Sport.column_names.delete("player_id")
		Sport.column_names.delete("updated_at")
		@fields=Sport.column_names
	end
	def show
		@sport=Sport.find params[:id]
	end

	def create
		@sport=Sport.new(sport_params)
		if @sport.save
			redirect_to sports_path
		else
			redirect_to new_sport_path
		end
	end
	def edit
		@sport=Sport.find params[:id]
		render "new"
	end
	def update
		@sport=Sport.find params[:id]
		if @sport.update_attributes(sport_params)
		flash[:notice]="The record was successfully updated"
		end
       redirect_to sports_path

	end
	def destroy
		@sport=Sport.find params[:id]
		if @sport.delete
		   flash[:notice]="The record is deleted successfully"
		   redirect_to sports_path
		end
	end


	def sport_manage_form
		@sport_fields=Sport.column_names
		if request.post?
			require 'rake'
			name=params[:field][:name]
			type=params[:field][:type]
			`rails g migration add_#{name}_to_sports #{name}:#{type}`
			`rake db:migrate`					
			Sport.reset_column_information
			@sport_fields=Sport.column_names
			flash[:notice]="The field added successfully"
		end
	end
	private

# Never trust parameters from the scary internet, only allow the white list through.
def sport_params
  params.require(:sport).permit!
end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_filter :login_required
	
	def index
		@tasks = Task.all
		render json: @tasks
	end

	def new
		@tasks = current_user.tasks
		@task = Task.new
	end

	def create
		@task = Task.new task_params
		@task.user = current_user
		if @task.save!
			flash[:notice] = "task created successfully"
			render "create"
		else
			flash[:notice] = "Error in task"
			redirect_to new_task_path
		end

	end
	def update
		@task = Task.find(params[:id])
		if @task.deleted
			@task.update_attributes(:deleted=>false)
			render json: @task
		else
			@task.update_attributes(:deleted=>true)
			render json: @task
		end
	end

	def update_task
		puts "the params are #{params}"
		@task = Task.find(params[:id])
		if @task
			@task.update_attributes(:name=>params[:name])
			render json: @task
		else
			
			render json: {:meassage =>"error"}
		end
	end

	private
	def task_params
		params.require(:task).permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/_admin_header.html.erb
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#page-top">Play It</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                    	<div class="dropdown">
                    		<button class="btn btn-default dropdown-toggle custom-button" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
   								 Sport
    							<span class="caret"></span>
  							</button>
  							<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
  								<li class="presentation"><%= link_to "Create Sport",new_sport_path%></li>
  								<li class="presentation"><%= link_to "List Sport",sports_path%></li>
  							</ul>
                    	</div>
                        
                    </li>
                    <li class="page-scroll">
                        <div class="dropdown">
                    		<button class="btn btn-default dropdown-toggle custom-button" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
   								 Player
    							<span class="caret"></span>
  							</button>
  							<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
  								<li class="presentation"><%= link_to "Create Player",new_player_path%></li>
  								<li class="presentation"><%= link_to "List Player",players_path%></li>
  							</ul>
                    	</div>
                    </li>
                    
                    <li class="page-scroll">
                        <%= link_to "Tasks",new_task_path%>
                    </li>
                    <li class="page-scroll">
                        <%= link_to "Post",posts_path%>
                    </li>
                    <% if user_signed_in? %>
  						<li class="page-scroll">
  							<%= link_to('Logout', destroy_user_session_path, :method => :delete) %> 
  						</li>
  						<li class="page-scroll">
  							<%= link_to 'Change Password', edit_user_registration_path %>       
  						</li>
  					<% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

app/views/layouts/_player_header.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('My sports', my_sports_path) %>        
  </li><br/>
  <li><%=link_to('New Tasks',new_task_path)%></li><br/>
  <li><%=link_to('My Tasks',player_path(current_user.player))%></li><br/>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li><br/>
  "hello i am <%=current_user.player.first_name%>"
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playit</title>
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="http://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" class="index"><%unless current_user.nil?%>
<%if current_user.admin?%>
<%=render "/layouts/admin_header"%>
<%else%>
<%=render "/layouts/player_header"%>
<%end%>
<%end%>
<section id="portfolio">
    <div class="container">
    	<div class="row">
			<%= yield %>
		</div>
	</div>
</section>
</body>
</html>

app/views/mailkick/subscriptions/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Subscriptions</title>

    <style>
      body {
        padding: 20px;
        font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
        font-size: 14px;
        line-height: 1.4;
      }

      a {
        color: blue;
      }

      .container {
        max-width: 500px;
        margin-left: auto;
        margin-right: auto;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <% if opted_out? %>
        <p>You are unsubscribed.</p>
        <p><%= link_to "Resubscribe", subscribe_url %></p>
      <% else %>
        <p>You are subscribed.</p>
        <p><%= link_to "Unsubscribe", unsubscribe_url %></p>
      <% end %>
    </div>
  </body>
</html>